teamforus/me-android

- presentation/src/main/java/io/forus/me/android/presentation/helpers/SystemServices.kt
> fix   fingerprintManager

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/account/AccountFragment.kt
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
> Send support dialog email

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This fixes the problem with building a generated signed APK
> downgrade gradle

- data/src/main/java/io/forus/me/android/data/entity/common/ApiError.java
- data/src/main/java/io/forus/me/android/data/entity/common/BaseError.java
- data/src/main/java/io/forus/me/android/data/exception/RetrofitExceptionMapper.java
- domain/src/main/java/io/forus/me/android/domain/exception/RetrofitExceptionMapper.java
- domain/src/main/java/io/forus/me/android/domain/models/records/errors/BaseApiError.java
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrActionProcessor.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/dialogs/ScanVoucherBaseErrorDialog.kt
https://github.com/teamforus/me/issues/409
> fix "No matching error message after scanning voucher"

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/ProviderFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/ProviderPartialChanges.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/ProviderPresenter.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/ProviderView.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/dialogs/organizations_dialog/OrganizationsAdapter.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/dialogs/organizations_dialog/OrganizationsListDialog.kt
- presentation/src/main/res/layout/view_organizations_list.xml
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
https://github.com/teamforus/me/issues/193
> Issue193 Organisation context switch

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/dialogs/VouchersApplySuccessDialog.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/ProviderFragment.kt
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
https://github.com/teamforus/me/issues/377
> issue377: better transaction Success modal

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/account/AccountFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/account/dialogs/LogoutDialog.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/lock/pin/PinLockFragment.kt
- presentation/src/main/res/layout/fragment_pinlock.xml
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
https://github.com/teamforus/me/issues/260
> Issue260 Move logout button

- presentation/src/main/res/layout/fragment_about_me.xml
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
https://github.com/teamforus/me/issues/385
> axissue385: fix text

- data/src/main/java/io/forus/me/android/data/entity/common/DetailsError.java
- data/src/main/java/io/forus/me/android/data/exception/RetrofitExceptionMapper.java
- domain/src/main/java/io/forus/me/android/domain/exception/RetrofitExceptionMapper.java
- domain/src/main/java/io/forus/me/android/domain/models/common/DetailsApiError.java
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrActionProcessor.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/ProviderFragment.kt
https://github.com/teamforus/me/issues/267
fix: instead hardcode "Transaction failed" will be show message from server such as "hoeveelheid dient minimaal .02 te zijn."
an backend error (http 422 403) handler  was added for transactions,
also added error handler foq QR scanner:
for  - qr_unexpected_error
- qr_popup_error (ScanVoucherNotEligibleDialog)
- qr_identity_expired
> Issue267 Implement backend error messages on transactions

- presentation/src/main/java/io/forus/me/android/presentation/view/base/NoInternetDialog.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/base/lr/LRFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/base/lr/LRPanelImpl.kt
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
https://github.com/teamforus/me/issues/259
> Issue259 Implement "No internet" error.

- data/src/main/java/io/forus/me/android/data/entity/sign/response/ShortTokenResult.java
- data/src/main/java/io/forus/me/android/data/net/sign/SignService.kt
- data/src/main/java/io/forus/me/android/data/repository/account/AccountRepository.kt
- data/src/main/java/io/forus/me/android/data/repository/account/datasource/AccountDataSource.kt
- data/src/main/java/io/forus/me/android/data/repository/account/datasource/local/AccountLocalDataSource.java
- data/src/main/java/io/forus/me/android/data/repository/account/datasource/remote/AccountRemoteDataSource.kt
- domain/src/main/java/io/forus/me/android/domain/repository/account/AccountRepository.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherModel.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherPartialChanges.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherPresenter.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherView.kt
https://github.com/teamforus/me/issues/379
> Issue379 Implement short token login 'voucher info'

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrActionProcessor.kt
not sure why new branch but yeah
> fix https://github.com/teamforus/me-android/pull/181

- presentation/src/main/java/io/forus/me/android/presentation/view/base/lr/LRFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/account/dialogs/SessionExpiredDialog.kt
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
https://github.com/teamforus/me/issues/388
> Issue388 Expired session

- data/src/main/java/io/forus/me/android/data/entity/vouchers/request/MakeDemoTransaction.java
- data/src/main/java/io/forus/me/android/data/entity/vouchers/response/DemoTransaction.java
- data/src/main/java/io/forus/me/android/data/net/vouchers/VouchersService.kt
- data/src/main/java/io/forus/me/android/data/repository/vouchers/VouchersRepository.kt
- data/src/main/java/io/forus/me/android/data/repository/vouchers/datasource/VouchersDataSource.kt
- data/src/main/java/io/forus/me/android/data/repository/vouchers/datasource/remote/VouchersRemoteDataSource.kt
- domain/src/main/java/io/forus/me/android/domain/models/qr/QrCode.kt
- domain/src/main/java/io/forus/me/android/domain/repository/vouchers/VouchersRepository.kt
- presentation/src/main/java/io/forus/me/android/presentation/qr/QrDecoder.kt
- presentation/src/main/java/io/forus/me/android/presentation/qr/QrDecoderResult.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrActionProcessor.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrScannerActivity.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/dialogs/ScanDemoTransactionDialog.kt
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
Provider signup. Test transaction implementation #343
https://github.com/teamforus/me/issues/343
> issue343 Test transaction implementation

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrActionProcessor.kt
- presentation/src/main/res/values-nl/strings.xml
the same fix that was to the release branch made separately to dev
> fixed develop branch Error with string

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrActionProcessor.kt
when you scan 0€ voucher you'll get error
> Fix scan voucher

- presentation/src/main/res/layout/activity_check_email.xml
- presentation/src/main/res/layout/fragment_account_pair_device.xml
- "back" arrow added on the pair screen
- letter picture position fixed
> develop: fixed ui

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrActionProcessor.kt
when you scan 0€ voucher you'll get error
> fixed scanning empty voucher

- presentation/src/main/res/layout/fragment_account_pair_device.xml
today's crash fix
*btw guys, what's the right way to implement those fixes? like we have a **release** branch and **dev**. I have two options:
1. make 2 same fixes on 2 branches and push to them
2. fix from the dev branch, push to dev, then make PR to the release branch from dev
yesterday I went with the option 1
> fixUI fix error

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherFragment.kt
- presentation/src/main/res/layout/fragment_popup_qr.xml
- presentation/src/main/res/layout/layout_number_item.xml
https://github.com/teamforus/me/issues/431
> Fix voucher info button #431

- buildsystem/dependencies.gradle
- presentation/build.gradle
- presentation/src/main/java/io/forus/me/android/presentation/helpers/SharedPref.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/component/extension/ViewExtensions.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/component/snackbar/UpdateAppSnackbar.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/component/snackbar/UpdateAppSnackbarView.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/dashboard/DashboardActivity.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/dashboard/DashboardFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/main/MainActivity.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherFragment.kt
- presentation/src/main/res/drawable-hdpi/ic_google_play_store.xml
- presentation/src/main/res/layout/activity_main.xml
- presentation/src/main/res/layout/fragment_dashboard.xml
- presentation/src/main/res/layout/layout_snackbar_update_app.xml
- presentation/src/main/res/layout/view_snackbar_update_app.xml
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
https://github.com/teamforus/me/issues/226
> being able to force/ask user to update app #226

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/dialogs/FullscreenDialog.java
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/item/VoucherFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/provider/ProviderFragment.kt
- presentation/src/main/res/layout/dialog_fullscreen.xml
- presentation/src/main/res/layout/fragment_send_reports.xml
- presentation/src/main/res/values/styles.xml
> UI fixes for send crash reports screen #203

- presentation/src/main/res/layout/activity_check_email.xml
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
just a UI fixes for small screen
> Fix check email ui

- data/src/main/java/io/forus/me/android/data/net/MeHttpLoggingInterceptor.java
- data/src/main/java/io/forus/me/android/data/net/MeServiceFactory.java
https://github.com/teamforus/itsm/issues/186
> fix me-android logs access token to a log file

- data/src/main/java/io/forus/me/android/data/entity/common/ApiError.java
- data/src/main/java/io/forus/me/android/data/entity/sign/request/EmailValidateRequest.kt
- data/src/main/java/io/forus/me/android/data/entity/sign/response/ValidateEmail.java
- data/src/main/java/io/forus/me/android/data/entity/sign/response/ValidateEmailResult.java
- data/src/main/java/io/forus/me/android/data/exception/RetrofitExceptionMapper.java
- data/src/main/java/io/forus/me/android/data/net/sign/SignService.kt
- data/src/main/java/io/forus/me/android/data/repository/account/AccountRepository.kt
- data/src/main/java/io/forus/me/android/data/repository/account/datasource/AccountDataSource.kt
- data/src/main/java/io/forus/me/android/data/repository/account/datasource/local/AccountLocalDataSource.java
- data/src/main/java/io/forus/me/android/data/repository/account/datasource/remote/AccountRemoteDataSource.kt
- domain/src/main/java/io/forus/me/android/domain/exception/RetrofitExceptionMapper.java
- domain/src/main/java/io/forus/me/android/domain/models/account/ValidateEmail.kt
- domain/src/main/java/io/forus/me/android/domain/models/records/errors/EmailError.java
- domain/src/main/java/io/forus/me/android/domain/repository/account/AccountRepository.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/account/check_email/CheckEmailActivity.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/login_signup_account/ErrorDialog.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/login_signup_account/LogInSignUpFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/login_signup_account/LogInSignUpModel.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/login_signup_account/LogInSignUpPartialChanges.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/login_signup_account/LogInSignUpPresenter.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/login_signup_account/LogInSignUpView.kt
https://github.com/teamforus/me/issues/514
> fix restore login flow

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/qr/QrActionProcessor.kt
Add delay on scanning qr-code to login
https://github.com/teamforus/me/issues/531
> Issue531 Add delay on scanning qr-code to login

- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
> https://github.com/teamforus/me/issues/523

- presentation/src/main/res/layout/fragment_about_me.xml
- presentation/src/main/res/values-nl/strings.xml
- presentation/src/main/res/values/strings.xml
@maartenfv Translations based on the texts you provided. Can you double check?
> Fix UI aug 23 translations

- presentation/src/main/res/values/strings.xml
https://github.com/teamforus/APP-2023-make-me-app-great-again/issues/102
> fix privacy URL

- build.gradle
- buildsystem/ci.gradle
- buildsystem/dependencies.gradle
- data/build.gradle
- data/src/main/java/io/forus/me/android/data/net/MeHttpLoggingInterceptor.java
- data/src/main/java/io/forus/me/android/data/repository/vouchers/VouchersRepository.kt
- domain/build.gradle
- domain/src/main/java/io/forus/me/android/domain/interactor/UseCase.java
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- presentation/build.gradle
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/io/forus/me/android/presentation/AndroidApplication.kt
- presentation/src/main/java/io/forus/me/android/presentation/helpers/SystemServices.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/dashboard/DashboardActivity.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/lock/fingerprint/BiometricPromptManager.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/lock/fingerprint/FingerprintFragment.kt
- settings.gradle
This pull request updates the Android Gradle Plugin (AGP) to version 1.8.5 and resolves dependencies that are no longer supported due to the deprecation of JCenter. The following changes have been made:
1. Updated AGP:
- Upgraded Android Gradle Plugin to version 1.8.5.
2. Resolved Dependencies:
- Arrow:
- Replaced with native tools as it is no longer supported. [Link](https://github.com/android10/arrow)
- Android Fingerprint Authentication:
-  Introduced a new biometric authentication window using BiometricPrompt for Android 9 (API Level 28) and above. The FingerprintFragment class required a complete rewrite to align with the latest best practices. [Link](https://github.com/msoftware/android-fingerprint-authentication)
- InkPageIndicator:
- Removed this library as it was unused in the …
> Update AGP and Resolve Deprecated Dependencies

- presentation/build.gradle
com.google.firebase:firebase-auth-ktx and was updated to latest versions. 
[](https://github.com/teamforus/APP-2023-make-me-app-great-again/issues/94)
> Issue "security vulnerability was discovered in reCAPTCHA Enterprise for Mobile"

- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/transactions_log/TransactionsActivity.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/transactions_log/adapter/TransactionsLogAdapter.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/transactions_log/details/TransactionDetailsFragment.kt
- presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/transactions_log/utils/TransactionsConst.kt
- presentation/src/main/res/drawable/bg_bottom_sheet_gray.xml
- presentation/src/main/res/layout/fragment_popup_transaction_details.xml
- presentation/src/main/res/values/styles.xml
TransactionDetailsFragment popup:
- fixed date format
- impowed UI and theme
> TransactionsList: fixed date format
